<?php

return [
    'customers' => [
        [
            'name' => 'Alessandro',
            'lastname' => 'Conti',
            'city' => 'Rome',
            'eye_color' => 'Brown',
            'hair_color' => 'Black',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Giulia',
            'lastname' => 'Rossi',
            'city' => 'Florence',
            'eye_color' => 'Blue',
            'hair_color' => 'Medium Blonde',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Lorenzo',
            'lastname' => 'Greco',
            'city' => 'Naples',
            'eye_color' => 'Green',
            'hair_color' => 'Light Brown',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Valentina',
            'lastname' => 'Bianchi',
            'city' => 'Milan',
            'eye_color' => 'Brown',
            'hair_color' => 'Black',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Gabriele',
            'lastname' => 'Rizzo',
            'city' => 'Palermo',
            'eye_color' => 'Hazel',
            'hair_color' => 'Light Brown',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Sofia',
            'lastname' => 'Gallo',
            'city' => 'Turin',
            'eye_color' => 'Brown',
            'hair_color' => 'Black',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Matteo',
            'lastname' => 'Moretti',
            'city' => 'Venice',
            'eye_color' => 'Green',
            'hair_color' => 'Dark Brown',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Caterina',
            'lastname' => 'Neri',
            'city' => 'Bologna',
            'eye_color' => 'Brown',
            'hair_color' => 'Black',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Antonio',
            'lastname' => 'Lombardi',
            'city' => 'Genoa',
            'eye_color' => 'Blue',
            'hair_color' => 'Light Blonde',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'Ginevra',
            'lastname' => 'Ferrari',
            'city' => 'Verona',
            'eye_color' => 'Brown',
            'hair_color' => 'Black',
            'citizenship' => 'Italian',
        ],
        [
            'name' => 'John',
            'lastname' => 'Doe',
            'city' => 'San Francisco',
            'eye_color' => 'Green',
            'hair_color' => 'Medium Brown',
            'citizenship' => 'American',
        ],
        [
            'name' => 'Diana',
            'lastname' => 'Prince',
            'city' => 'Los Angeles',
            'eye_color' => 'Brown',
            'hair_color' => 'Black',
            'citizenship' => 'American',
        ],
        [
            'name' => 'Clark',
            'lastname' => 'Kent',
            'city' => 'Metropolis',
            'eye_color' => 'Blue',
            'hair_color' => 'Dark Brown',
            'citizenship' => 'American',
        ],
    ]


];
